---
- name: Create an s3 bucket on AWS with Ansible
  hosts: localhost
  connection: local
  
  vars_files:
          - ~/cred.zon
  tasks:
          - name: 
            amazon.aws.aws_s3:
              bucket: ducktoaster77    # naming rules https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html#bucketnamingrules
              mode: delete
              permission: public-read
              aws_access_key: "{{ ec2_access_key }}"
              aws_secret_key: "{{ ec2_secret_key }}"
