---
# tasks file for roles/precheck-crqid
- name: PRECHECK PHASE - Request CRQid
  block:

        - name: Pause play until a URL is reachable from this host
          uri:
            url: http://0.0.0.0:9876/crid
            follow_redirects: none
            method: GET
          register: result
          until: result.status == 200
          retries: 24 # 5 seconds * 24 retries
          delay: 5 # Every 5 seconds

        - name: Show the value we captured
          debug:
                  var: result.json
                  verbosity: 1

  rescue:
        - name: PRECHECK PHASE - FAILED
          fail:
                  msg: "PRECHECK PHASE FAILED. Nothing to roll back... EXITING."
