---
# tasks file for roles/precheck-isilon
- name: Precheck Operations - Isilon / PowerScale
  block:
          - name: Gather facts on Isilon cluster
            dellemc_isilon_gatherfacts:
                    onefs_host: "{{ onefs_host }}"
                    port_no: "{{ isilon_port }}"
                    verify_ssl: "{{ verify_ssl }}"
                    api_user: "{{ api_user }}"
                    api_password: "{{ api_password }}"
                    gather_subset:
                            - attributes
            register: results


          - name: PRECHECK - Correct number of devices enrolled
            fail:
                    msg: "Precheck fail."
            when: results.Attributes.Config.devices|length != 4


          - name: PRECHECK - Ensure correct release version running on Cluster
            fail:
                    msg: "Precheck failure."
            when: item.release != "v8.2.1.0"
            loop: "{{ results.Attributes.Cluster_Version.nodes }}"
            loop_control:
                    label: "{{ item.release }}"


          - name: PRECHECK - Ensure no current failures on the Isilon / Powerscale Cluster
            fail:
                    msg: "Precheck failure."
            when: results.Attributes.Cluster_Version.errors | length != 0
